# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

buildLFactors <- function(t, h1, h2) {
    .Call(`_binnednp_buildLFactors`, t, h1, h2)
}

calcw_cpp <- function(xb, y) {
    .Call(`_binnednp_calcw_cpp`, xb, y)
}

Window_helper <- function(b, xb, y, t, Lfactors, J1_b, J2_b) {
    .Call(`_binnednp_Window_helper`, b, xb, y, t, Lfactors, J1_b, J2_b)
}

main_method_np <- function(hn, B, hseq, xbm, y, t, MSE_J1, MSE_J2, J1_np, J2_np, J1b, J2b) {
    invisible(.Call(`_binnednp_main_method_np`, hn, B, hseq, xbm, y, t, MSE_J1, MSE_J2, J1_np, J2_np, J1b, J2b))
}

pnorm_cpp <- function(x) {
    .Call(`_binnednp_pnorm_cpp`, x)
}

Fg <- function(x, w, t, g) {
    .Call(`_binnednp_Fg`, x, w, t, g)
}

biasFh <- function(x, n, t, w, p, g, h) {
    .Call(`_binnednp_biasFh`, x, n, t, w, p, g, h)
}

varFh <- function(x, n, t, p, h) {
    .Call(`_binnednp_varFh`, x, n, t, p, h)
}

mise_Fh <- function(h, n, t, w, p, g, lgrid, lim1, lim2) {
    .Call(`_binnednp_mise_Fh`, h, n, t, w, p, g, lgrid, lim1, lim2)
}

boot_bw_dist <- function(nit, h0, h1, rho, n, t, w, p, g, lgrid, lim1, lim2) {
    .Call(`_binnednp_boot_bw_dist`, nit, h0, h1, rho, n, t, w, p, g, lgrid, lim1, lim2)
}

dnorm_cpp <- function(x) {
    .Call(`_binnednp_dnorm_cpp`, x)
}

dnorm_d2_cpp <- function(x) {
    .Call(`_binnednp_dnorm_d2_cpp`, x)
}

fh_combt <- function(x, t, w, h) {
    .Call(`_binnednp_fh_combt`, x, t, w, h)
}

fh_combt_d2 <- function(x, t, w, h) {
    .Call(`_binnednp_fh_combt_d2`, x, t, w, h)
}

curv_cpp <- function(t, w, h, lim1, lim2, lgrid) {
    .Call(`_binnednp_curv_cpp`, t, w, h, lim1, lim2, lgrid)
}

dicoto_lambda <- function(lambda, nith, h0, h1, rho, hist, combt, combw, lim1, lim2) {
    .Call(`_binnednp_dicoto_lambda`, lambda, nith, h0, h1, rho, hist, combt, combw, lim1, lim2)
}

zeta_hist_p <- function(hist, combt, comby, combw, Af2_mixt, l0, l1, h0, h1, lrho, rho, nitlambda, nith, lim1, lim2) {
    .Call(`_binnednp_zeta_hist_p`, hist, combt, comby, combw, Af2_mixt, l0, l1, h0, h1, lrho, rho, nitlambda, nith, lim1, lim2)
}

pnorm_cpp_fun <- function(x) {
    .Call(`_binnednp_pnorm_cpp_fun`, x)
}

dnorm_d1_cpp <- function(x) {
    .Call(`_binnednp_dnorm_d1_cpp`, x)
}

Fh_combt <- function(x, t, w, h) {
    .Call(`_binnednp_Fh_combt`, x, t, w, h)
}

fh_combt_d1 <- function(x, t, w, h) {
    .Call(`_binnednp_fh_combt_d1`, x, t, w, h)
}

slope_cpp <- function(t, w, h, lim1, lim2, lgrid) {
    .Call(`_binnednp_slope_cpp`, t, w, h, lim1, lim2, lgrid)
}

dicoto_lambda_dist <- function(lambda, nith, h0, h1, rho, emp, comby, combt, combw, lim1, lim2) {
    .Call(`_binnednp_dicoto_lambda_dist`, lambda, nith, h0, h1, rho, emp, comby, combt, combw, lim1, lim2)
}

zeta_hist_p_dist <- function(emp, combt, comby, combw, Af1_mixt, l0, l1, h0, h1, lrho, rho, nitlambda, nith, lim1, lim2) {
    .Call(`_binnednp_zeta_hist_p_dist`, emp, combt, comby, combw, Af1_mixt, l0, l1, h0, h1, lrho, rho, nitlambda, nith, lim1, lim2)
}

gaussian_mise_initialize <- function(n, k, wg, w, t, gboot, AK) {
    invisible(.Call(`_binnednp_gaussian_mise_initialize`, n, k, wg, w, t, gboot, AK))
}

gaussian_mise <- function(h) {
    .Call(`_binnednp_gaussian_mise`, h)
}

gaussian_mise_loop <- function(hn, seq, rho) {
    .Call(`_binnednp_gaussian_mise_loop`, hn, seq, rho)
}

gaussian_dichotomy <- function(hn, t) {
    .Call(`_binnednp_gaussian_dichotomy`, hn, t)
}

